[project]
name = "pac-man"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "arcade>=3.3.3",
    "flake8>=7.3.0",
    "mazegenerator @ file:///${PROJECT_ROOT}/lib/mazegenerator-2.0.1-py3-none-any.whl",
    "mypy>=2.1.0",
    "pydantic>=2.13.4",
]

[tool.pytest.ini_options]
pythonpath = ["."]

[[tool.mypy.overrides]]
module = ["mazegenerator.*"]
ignore_missing_imports = true
